# Generated by Django 4.1.7 on 2023-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('R', 'red'), ('B', 'blue')], max_length=1, null=True, verbose_name='رنگ محصول'),
        ),
        migrations.AlterField(
            model_name='producttag',
            name='title',
            field=models.CharField(max_length=25, verbose_name='عنوان تگ'),
        ),
    ]
