# Generated by Django 4.1.7 on 2023-03-21 12:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_color_alter_producttag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=18, null=True, samples=None, verbose_name='رنگ محصول'),
        ),
    ]
