# Generated by Django 4.1.7 on 2023-03-21 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_delete',
        ),
    ]
