# Generated by Django 4.1.7 on 2023-03-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0006_remove_product_color_productcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال / غیرفعال'),
        ),
    ]
