# Generated by Django 4.1.7 on 2023-03-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0008_productcategory_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='title',
            field=models.CharField(max_length=30, verbose_name='نام دسته بندی محصول'),
        ),
    ]
