# Generated by Django 4.1.7 on 2023-03-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0009_alter_productcategory_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGrind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام دستگاه آسیاب')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=300, unique=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='product',
            name='grind_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.productgrind', verbose_name='انتخاب سایز آسیاب قهوه'),
        ),
    ]
