# Generated by Django 4.1.7 on 2023-03-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_productgrind_alter_product_title_product_grind_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgrind',
            options={'verbose_name': 'آسیاب', 'verbose_name_plural': 'آسیاب های محصول'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='grind_size',
        ),
        migrations.AddField(
            model_name='product',
            name='grind_size',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.productgrind', verbose_name='انتخاب سایز آسیاب قهوه'),
        ),
    ]
