# Generated by Django 4.1.7 on 2023-03-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0012_remove_product_grind_size_remove_producttag_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttag',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='product_module.producttag', verbose_name='تگ های محصول'),
        ),
    ]
