# Generated by Django 4.1.7 on 2023-03-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0013_remove_producttag_product_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGrind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام دستگاه آسیاب')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'آسیاب',
                'verbose_name_plural': 'آسیاب های محصول',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-create_date'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AddField(
            model_name='product',
            name='grind',
            field=models.ManyToManyField(to='product_module.productgrind', verbose_name='انتخاب آسیاب برای محصول'),
        ),
    ]
