# Generated by Django 4.1.7 on 2023-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0015_alter_product_grind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grind',
        ),
        migrations.AddField(
            model_name='productgrind',
            name='grind',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.productgrind', verbose_name='انتخاب آسیاب برای محصول'),
        ),
    ]
