# Generated by Django 4.1.7 on 2023-03-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0016_remove_product_grind_productgrind_grind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgrind',
            name='grind',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.product', verbose_name='انتخاب آسیاب برای محصول'),
        ),
    ]
