# Generated by Django 4.1.7 on 2023-03-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0019_alter_product_grind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grind',
        ),
        migrations.DeleteModel(
            name='ProductGrind',
        ),
    ]
