# Generated by Django 4.1.7 on 2023-03-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0020_remove_product_grind_delete_productgrind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGrind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام دستگاه آسیاب')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'آسیاب محصول',
                'verbose_name_plural': 'آسیاب های محصولات',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='grind',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.productgrind', verbose_name='انتخاب دستگاه برای آسیاب'),
        ),
    ]
