# Generated by Django 4.1.7 on 2023-05-22 15:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0021_productgrind_product_grind'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=True, verbose_name='موجود / ناموجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(db_index=True, verbose_name='توضیحات'),
        ),
    ]
