# Generated by Django 4.1.7 on 2023-05-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0023_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='transportation_price',
            field=models.IntegerField(default=10, verbose_name='قیمت حمل و نقل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='قیمت محصول'),
        ),
    ]
