# Generated by Django 4.1.7 on 2023-05-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0027_alter_product_transportation_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='transportation_price',
        ),
    ]
