# Generated by Django 4.1.7 on 2023-05-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0028_remove_product_transportation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_count',
            field=models.IntegerField(default=10, verbose_name='تعداد موجودی محصول'),
        ),
    ]
