# Generated by Django 4.1.7 on 2023-05-30 14:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0030_alter_product_availability_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=18, null=True, samples=None, verbose_name='رنگ محصول'),
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
