# Generated by Django 4.1.7 on 2023-06-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0032_remove_product_color_productcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.productcolor', verbose_name='انتخاب رنگ برای محصول'),
        ),
    ]
