# Generated by Django 4.1.7 on 2023-06-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0037_alter_productcolor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='status',
            field=models.BooleanField(default=True, verbose_name='موجود / ناموجود'),
        ),
    ]
