# Generated by Django 4.1.7 on 2023-06-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0040_alter_product_availability_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability_count',
        ),
    ]
