# Generated by Django 4.1.7 on 2023-06-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0041_remove_product_availability_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grind',
        ),
        migrations.AddField(
            model_name='product',
            name='grind',
            field=models.CharField(choices=[('MOKAPAT', 'موکاپات'), ('CKEMECKS', 'کمکس'), ('MACHINE', 'دستگاه')], default='MOKAPAT', max_length=50, verbose_name='آسیاب'),
        ),
    ]
