# Generated by Django 4.1.7 on 2023-06-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0042_remove_product_grind_product_grind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grind',
        ),
        migrations.AddField(
            model_name='product',
            name='grind',
            field=models.ManyToManyField(blank=True, null=True, to='product_module.productgrind', verbose_name='انتخاب دستگاه برای آسیاب'),
        ),
    ]
