# Generated by Django 4.1.7 on 2023-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0044_product_availability_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability_count',
            field=models.PositiveIntegerField(blank=True, help_text='- به غیر از محصولاتی که رنگ دارند', null=True, verbose_name='تعداد موجودی محصول'),
        ),
    ]
