# Generated by Django 4.1.7 on 2023-10-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0047_remove_coupon_used_by_coupon_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.IntegerField(default=0, verbose_name='تعداد استفاده'),
        ),
    ]
