# Generated by Django 4.1.7 on 2023-10-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0049_alter_coupon_used_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='used_count',
        ),
    ]
