# Generated by Django 4.1.7 on 2023-11-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0050_remove_coupon_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='title',
            field=models.CharField(default='12', max_length=100, verbose_name='عنوان'),
        ),
    ]
