# Generated by Django 4.1.7 on 2023-06-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.PositiveBigIntegerField(verbose_name='شماره موبایل'),
        ),
    ]
