# Generated by Django 4.1.7 on 2023-07-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0005_alter_address_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SHIPPED', 'ارسال شده'), ('PENDING', 'انتظار'), ('PROCESSING', 'در حال پردازش')], default='PENDING', max_length=30),
        ),
    ]
