# Generated by Django 4.1.7 on 2023-07-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ارسال شده', 'SHIPPED'), ('انتظار', 'PENDING'), ('در حال پردازش', 'PROCESSING')], default='PENDING', max_length=30),
        ),
    ]
