# Generated by Django 4.1.7 on 2023-07-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'ارسال شده'), ('pending', 'انتظار'), ('processing', 'در حال پردازش')], default='pending', max_length=30, verbose_name='وضعیت سفارش'),
        ),
    ]
