# Generated by Django 4.1.7 on 2023-07-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ارسال شده', 'Shipped'), ('انتظار', 'Pending'), ('در حال پردازش', 'Processing')], default='انتظار', max_length=30, verbose_name='وضعیت سفارش'),
        ),
    ]
