# Generated by Django 4.1.7 on 2023-07-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ارسال شده', 'ارسال شده'), ('انتظار', 'انتظار'), ('در حال پردازش', 'در حال پردازش')], default='pending', max_length=30, verbose_name='وضعیت سفارش'),
        ),
    ]
