# Generated by Django 4.1.7 on 2023-08-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0013_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wholesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('landline_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره ثابت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('full_address', models.TextField(verbose_name='آدرس کامل')),
                ('product', models.TextField(verbose_name='جزییات کامل سفارش')),
            ],
        ),
    ]
