# Generated by Django 4.1.7 on 2023-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0014_wholesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesale',
            name='order_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ سفارش'),
        ),
        migrations.AddField(
            model_name='wholesale',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده / نشده'),
        ),
        migrations.AddField(
            model_name='wholesale',
            name='statement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='بیانه'),
        ),
        migrations.AddField(
            model_name='wholesale',
            name='status',
            field=models.CharField(choices=[('ارسال شده', 'ارسال شده'), ('انتظار', 'انتظار'), ('در حال پردازش', 'در حال پردازش')], default='انتظار', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='wholesale',
            name='total_paid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کل مبلغ پرداخت'),
        ),
    ]
