# Generated by Django 4.1.7 on 2023-08-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0015_wholesale_order_date_wholesale_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesale',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ سفارش'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='total_paid',
            field=models.CharField(max_length=50, verbose_name='کل مبلغ پرداخت'),
        ),
    ]
