# Generated by Django 4.1.7 on 2023-08-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0016_alter_wholesale_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesale',
            name='statement',
            field=models.PositiveBigIntegerField(blank=True, max_length=100, null=True, verbose_name='بیانه'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='total_paid',
            field=models.PositiveBigIntegerField(max_length=50, verbose_name='کل مبلغ پرداخت'),
        ),
    ]
