# Generated by Django 4.1.7 on 2023-08-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0017_alter_wholesale_statement_alter_wholesale_total_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesale',
            name='statement',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='بیانه'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='total_paid',
            field=models.PositiveBigIntegerField(verbose_name='کل مبلغ پرداخت'),
        ),
    ]
