# Generated by Django 4.1.7 on 2023-08-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0019_remove_wholesale_total_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesale',
            name='total_amount_paid',
            field=models.PositiveBigIntegerField(verbose_name='کل مبلغ پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='total_amount_payable',
            field=models.PositiveBigIntegerField(verbose_name='کل مبلغ قابل پرداخت'),
        ),
    ]
