# Generated by Django 4.1.7 on 2023-08-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0020_alter_wholesale_total_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesale',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='شماره موبایل'),
        ),
    ]
