# Generated by Django 4.1.7 on 2023-10-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0022_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
