# Generated by Django 4.1.7 on 2023-10-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0023_remove_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payable_amount',
            field=models.BigIntegerField(default=12, verbose_name='قیمت نهایی پرداخت شده'),
        ),
    ]
