# Generated by Django 4.1.7 on 2023-10-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0024_order_payable_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payable_amount',
            field=models.BigIntegerField(verbose_name='قیمت نهایی پرداخت شده'),
        ),
    ]
