# Generated by Django 4.1.7 on 2023-10-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0025_alter_order_payable_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payable_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت نهایی پرداخت شده'),
        ),
    ]
