# Generated by Django 4.1.7 on 2023-10-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0027_remove_order_payable_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='payable_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='payable_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت نهایی پرداخت شده'),
        ),
    ]
