# Generated by Django 4.1.7 on 2023-10-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0028_remove_orderdetail_payable_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
    ]
