# Generated by Django 4.1.7 on 2023-10-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_module', '0017_remove_transaction_order'),
        ('order_module', '0031_alter_order_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_module.transaction', verbose_name='تراکنش کیف پول'),
        ),
    ]
