# Generated by Django 4.1.7 on 2023-10-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0032_alter_order_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
    ]
