# Generated by Django 4.1.7 on 2023-10-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0033_remove_order_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_amount',
            field=models.BigIntegerField(default=1, verbose_name='مبلغ تراکنش کیف پول'),
        ),
    ]
