# Generated by Django 4.1.7 on 2023-10-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0034_order_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_amount',
            field=models.BigIntegerField(verbose_name='مبلغ تراکنش کیف پول'),
        ),
    ]
