# Generated by Django 4.1.7 on 2023-10-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0035_alter_order_transaction_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_amount',
            field=models.BigIntegerField(default=0, verbose_name='مبلغ تراکنش کیف پول'),
        ),
    ]
