# Generated by Django 4.1.7 on 2023-11-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0037_alter_order_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد تخفیف استفاده شده'),
        ),
    ]
