from django.urls import path, re_path

from admin_panel import views

urlpatterns = [
    path('', views.index_admin_panel, name='index_admin_page'),
    path('contacts/', views.AdminContactUsList.as_view(), name='contact_list_admin_page'),
    path('contacts/detail/<int:pk>', views.AdminContactUsDetail.as_view(), name='contact_detail_admin_page'),
    path('contacts/delete/<int:pk>', views.delete_contact, name='contact_delete_admin_page'),
    path('products/top-selling', views.top_selling_product, name='top_selling_products_admin_page'),
    path('products/delete/<int:pk>', views.delete_product, name='product_delete_admin_page'),
    path('products/', views.AdminProductList.as_view(), name='product_list_admin_page'),
    path('products/edit/<int:pk>', views.EditeAdminProduct.as_view(), name='edit_product_admin_page'),
    path('products/add/', views.AddProductAdmin.as_view(), name='add_product_admin_page'),
    path('products/gallery/delete/<int:pk>', views.delete_gallery, name='gallery_delete_admin_page'),
    path('products/galleries/', views.AdminProductGalleryList.as_view(), name='product_gallery_list_admin_page'),
    path('products/gallery/add/', views.AddProductGallery.as_view(), name='add_product_gallery_admin_page'),
    path('products/gallery/edit/<int:pk>', views.EditeAdminProductGallery.as_view(),
         name='edit_product_gallery_admin_page'),
    path('products/color/delete/<int:pk>', views.delete_color, name='color_delete_admin_page'),
    path('products/colors/', views.AdminProductColorList.as_view(), name='product_color_list_admin_page'),
    path('products/color/add/', views.AddProductColor.as_view(), name='add_product_color_admin_page'),
    path('products/color/edit/<int:pk>', views.EditeAdminProductColor.as_view(), name='edit_product_color_admin_page'),
    path('products/grind/delete/<int:pk>', views.delete_grind, name='grind_delete_admin_page'),
    path('products/grinds/', views.AdminProductGrindList.as_view(), name='product_grind_list_admin_page'),
    path('products/grind/add/', views.AddProductGrind.as_view(), name='add_product_grind_admin_page'),
    path('products/grind/edit/<int:pk>', views.EditeAdminProductGrind.as_view(), name='edit_product_grind_admin_page'),
    path('products/tag/delete/<int:pk>', views.delete_tag, name='tag_delete_admin_page'),
    path('products/tags/', views.AdminProductTagList.as_view(), name='product_tag_list_admin_page'),
    path('products/tag/add/', views.AddProductTag.as_view(), name='add_product_tag_admin_page'),
    path('products/tag/edit/<int:pk>', views.EditeAdminProductTag.as_view(), name='edit_product_tag_admin_page'),
    path('products/category/delete/<int:pk>', views.delete_category, name='category_delete_admin_page'),
    path('products/categories/', views.AdminProductCategoryList.as_view(), name='product_category_list_admin_page'),
    path('products/category/add/', views.AddProductCategory.as_view(), name='add_product_category_admin_page'),
    path('products/category/edit/<int:pk>', views.EditeAdminProductCategory.as_view(),
         name='edit_product_category_admin_page'),
    path('articles/top-articles', views.most_view_articles, name='most_viewed_articles_admin_page'),
    path('articles/categories/', views.AdminArticleCategoryList.as_view(), name='article_category_list_admin_page'),
    path('articles/category/edit/<int:pk>', views.EditAdminArticleCategory.as_view(),
         name='edit_article_category_admin_page'),
    path('articles/category/add/', views.AddArticleCategoryAdmin.as_view(), name='add_article_category_admin_page'),
    path('articles/category/delete/<int:pk>', views.delete_article_category, name='article_category_delete_admin_page'),
    path('articles/tags/', views.AdminArticleTagList.as_view(), name='article_tag_list_admin_page'),
    path('articles/tag/edit/<int:pk>', views.EditAdminArticleTag.as_view(), name='edit_article_tag_admin_page'),
    path('articles/tag/add/', views.AddArticleTagAdmin.as_view(), name='add_article_tag_admin_page'),
    path('articles/tag/delete/<int:pk>', views.delete_article_tag, name='article_tag_delete_admin_page'),
    path('articles/', views.AdminArticleList.as_view(), name='article_list_admin_page'),
    path('articles/add/', views.AddArticleAdmin.as_view(), name='add_article_admin_page'),
    path('articles/edit/<int:pk>', views.EditArticleAdmin.as_view(), name='edit_article_admin_page'),
    path('articles/delete/<int:pk>', views.delete_article, name='article_delete_admin_page'),
    path('site-settings/', views.SiteSettingAdminList.as_view(), name='site_setting_list_admin_page'),
    path('site-settings/add/', views.AddSiteSettingAdmin.as_view(), name='add_site_setting_admin_page'),
    path('site-settings/edit/<int:pk>', views.EditAdminSiteSetting.as_view(), name='edit_site_setting_admin_page'),
    path('site-settings/delete/<int:pk>', views.delete_site_setting, name='site_setting_delete_admin_page'),
    path('site-banners/', views.SiteBannerAdminList.as_view(), name='site_banner_list_admin_page'),
    path('site-banners/add/', views.AddSiteBannerAdmin.as_view(), name='add_site_banner_admin_page'),
    path('site-banners/edit/<int:pk>', views.EditAdminSiteBanner.as_view(), name='edit_site_banner_admin_page'),
    path('site-banners/delete/<int:pk>', views.delete_site_banner, name='site_banner_delete_admin_page'),
    path('site-social-medias/', views.SiteSocialAdminList.as_view(), name='site_social_list_admin_page'),
    path('site-social-medias/add/', views.AddSiteSocialAdmin.as_view(), name='add_site_social_admin_page'),
    path('site-social-medias/edit/<int:pk>', views.EditAdminSiteSocial.as_view(), name='edit_site_social_admin_page'),
    path('site-social-medias/delete/<int:pk>', views.delete_site_social, name='site_social_delete_admin_page'),
    path('site-top-products/', views.SiteTopProductAdminList.as_view(), name='site_top_product_list_admin_page'),
    path('site-top-products/add/', views.AddSiteTopProductAdmin.as_view(), name='add_site_top_product_admin_page'),
    path('site-top-products/edit/<int:pk>', views.EditAdminSiteTopProduct.as_view(),
         name='edit_site_top_product_admin_page'),
    path('site-top-products/delete/<int:pk>', views.delete_site_top_product, name='site_top_product_delete_admin_page'),
    path('site-categories/', views.SiteCategoryAdminList.as_view(), name='site_category_list_admin_page'),
    path('site-categories/add/', views.AddSiteCategoryAdmin.as_view(), name='add_site_category_admin_page'),
    path('site-categories/edit/<int:pk>', views.EditAdminSiteCategory.as_view(), name='edit_site_category_admin_page'),
    path('site-categories/delete/<int:pk>', views.delete_site_category, name='site_category_delete_admin_page'),
    path('site-footer-boxes/', views.SiteFooterBoxAdminList.as_view(), name='site_footer_box_list_admin_page'),
    path('site-footer-boxes/add/', views.AddSiteFooterBoxAdmin.as_view(), name='add_site_footer_box_admin_page'),
    path('site-footer-boxes/edit/<int:pk>', views.EditAdminSiteFooterBox.as_view(),
         name='edit_site_footer_box_admin_page'),
    path('site-footer-boxes/delete/<int:pk>', views.delete_site_footer_box, name='site_footer_box_delete_admin_page'),
    path('site-footer-links/', views.SiteFooterLinkAdminList.as_view(), name='site_footer_link_list_admin_page'),
    path('site-footer-links/add/', views.AddSiteFooterLinkAdmin.as_view(), name='add_site_footer_link_admin_page'),
    path('site-footer-links/edit/<int:pk>', views.EditAdminSiteFooterLink.as_view(),
         name='edit_site_footer_link_admin_page'),
    path('site-footer-links/delete/<int:pk>', views.delete_site_footer_link, name='site_footer_link_delete_admin_page'),
    path('orders/', views.OrderAdminList.as_view(), name='order_list_admin_page'),
    path('orders/edit/<int:pk>', views.EditOrderAdmin.as_view(), name='edit_order_admin_page'),
    path('orders/delete/<int:pk>', views.delete_order, name='order_delete_admin_page'),
    path('orders/order-detail/delete/<int:pk>', views.delete_order_detail, name='order_detail_delete_admin_page'),
    path('orders/invoice/<int:pk>', views.invoice_order, name='order_invoice_admin_page'),
    path('wholesales/', views.WholesaleAdminList.as_view(), name='wholesale_list_admin_page'),
    path('wholesales/add/', views.AddWholesaleAdmin.as_view(), name='add_wholesale_admin_page'),
    path('wholesales/edit/<int:pk>', views.EditAdminWholesale.as_view(), name='edit_wholesale_admin_page'),
    path('wholesales/delete/<int:pk>', views.delete_wholesale, name='wholesale_delete_admin_page'),
    path('wholesales/invoice/<int:pk>', views.invoice_wholesale, name='wholesale_invoice_admin_page'),
    path('users/', views.UserAdminList.as_view(), name='user_list_admin_page'),
    path('users/add/', views.AddUserAdmin.as_view(), name='add_user_admin_page'),
    path('users/login/', views.LoginUserAdmin.as_view(), name='login_user_admin_page'),
    path('users/change-password/', views.ChangePasswordUserAdmin.as_view(), name='change_pass_user_admin_page'),
    path('users/logout/', views.logout_user_admin, name='logout_user_admin_page'),
    path('users/edit/<int:pk>', views.EditAdminUser.as_view(), name='edit_user_admin_page'),
    path('users/delete/<int:pk>', views.delete_user, name='user_delete_admin_page'),
    path('addresses/', views.AddressAdminList.as_view(), name='address_list_admin_page'),
    path('addresses/add/', views.AddAddressAdmin.as_view(), name='add_address_admin_page'),
    path('addresses/edit/<int:pk>', views.EditAdminAddress.as_view(), name='edit_address_admin_page'),
    path('addresses/delete/<int:pk>', views.delete_address, name='address_delete_admin_page'),
    path('wallets/', views.WalletAdminList.as_view(), name='wallet_list_admin_page'),
    path('wallets/add/', views.AddWalletAdmin.as_view(), name='add_wallet_admin_page'),
    path('wallets/edit/<int:pk>', views.EditAdminWallet.as_view(), name='edit_wallet_admin_page'),
    path('wallets/delete/<int:pk>', views.delete_wallet, name='wallet_delete_admin_page'),
    path('wallet/transactions/', views.TransactionWalletAdminList.as_view(), name='transaction_wallet_list_admin_page'),
    path('wallet/transactions/add/', views.AddTransactionWalletAdmin.as_view(),
         name='add_transaction_wallet_admin_page'),
    path('wallet/transactions/edit/<int:pk>', views.EditAdminTransactionWallet.as_view(),
         name='edit_transaction_wallet_admin_page'),
    path('wallet/transactions/delete/<int:pk>', views.delete_transaction_wallet,
         name='transaction_wallet_delete_admin_page'),
    path('wallet/settings/', views.WalletSettingAdminList.as_view(), name='wallet_setting_list_admin_page'),
    path('wallet/settings/edit/<int:pk>', views.EditWalletSetting.as_view(), name='edit_wallet_setting_admin_page'),
    path('coupons/', views.CouponAdminList.as_view(), name='coupon_list_admin_page'),
    path('coupons/add/', views.AddCouponAdmin.as_view(), name='add_coupon_admin_page'),
    path('coupons/edit/<int:pk>', views.EditAdminCoupon.as_view(), name='edit_coupon_admin_page'),
    path('coupons/delete/<int:pk>', views.delete_coupon, name='coupon_delete_admin_page'),
]
