# Generated by Django 4.1.7 on 2023-04-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_footerlinkbox_footerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان بنر')),
                ('url', models.URLField(max_length=500, verbose_name='آدرس ulr بنر')),
                ('image', models.ImageField(upload_to='images/banners', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیرفعال')),
                ('position', models.CharField(choices=[('product_list', 'صفحه لیست محصولات')], max_length=200, verbose_name='محل قرار گیری بنر در سایت')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنر های تبلیغاتی',
            },
        ),
    ]
