# Generated by Django 4.1.7 on 2023-04-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_alter_sitesetting_footer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_image',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_us_image',
            field=models.ImageField(default=None, upload_to='images/site_setting', verbose_name='تصویر در صفحه درباره ما'),
        ),
    ]
