# Generated by Django 4.1.7 on 2023-04-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0007_alter_sitesetting_about_us_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_us_image',
        ),
    ]
