# Generated by Django 4.1.7 on 2023-04-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0008_remove_sitesetting_about_us_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='footer_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/site_setting', verbose_name='تصویر پس زمینه فوتر سایت'),
        ),
    ]
