# Generated by Django 4.1.7 on 2023-04-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0009_sitesetting_footer_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='footer_image',
        ),
    ]
