# Generated by Django 4.1.7 on 2023-04-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0013_sitesetting_site_icon_circle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_icon_circle',
            field=models.ImageField(blank=True, null=True, upload_to='images/site_setting', verbose_name='لوگوی دایره ای سایت'),
        ),
    ]
