# Generated by Django 4.1.7 on 2023-05-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0023_alter_product_options'),
        ('site_module', '0014_alter_sitesetting_site_icon_circle'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('short_description', models.CharField(max_length=300, verbose_name='توضیحات کوتاه')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.productcategory', verbose_name='دسته بندی محصول')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول در سایت',
                'verbose_name_plural': 'دسته بندی های محصول در سایت',
            },
        ),
    ]
