# Generated by Django 4.1.7 on 2023-05-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0016_sitesettingcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettingcategory',
            name='image',
            field=models.ImageField(default=None, upload_to='images/site_setting', verbose_name='تصویر'),
        ),
    ]
