# Generated by Django 4.1.7 on 2023-05-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0017_sitesettingcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettingcategory',
            name='image',
            field=models.ImageField(upload_to='images/site_setting', verbose_name='تصویر'),
        ),
    ]
