# Generated by Django 4.1.7 on 2023-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0021_topproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=50, verbose_name='آیدی اینستاگرام')),
                ('telegram', models.CharField(max_length=50, verbose_name='آیدی تلگرام')),
                ('whatsapp', models.CharField(max_length=50, verbose_name='آیدی واتساپ')),
                ('youtube', models.CharField(max_length=130, verbose_name='آدرس یوتیوب')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.AlterModelOptions(
            name='topproduct',
            options={'verbose_name': 'محصول برتر', 'verbose_name_plural': 'محصولات برتر'},
        ),
    ]
