# Generated by Django 4.1.7 on 2023-07-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0022_socialmedia_alter_topproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
