# Generated by Django 4.1.7 on 2023-07-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0023_socialmedia_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آیدی اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آیدی تلگرام'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='آیدی واتساپ'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='youtube',
            field=models.CharField(blank=True, max_length=130, null=True, verbose_name='آدرس یوتیوب'),
        ),
    ]
