# Generated by Django 4.1.7 on 2023-08-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0024_alter_socialmedia_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='position',
            field=models.CharField(choices=[('product_list', 'صفحه لیست محصولات'), ('product_detail', 'صفحه جزییات محصولات')], max_length=200, verbose_name='محل قرار گیری بنر در سایت'),
        ),
    ]
