# Generated by Django 4.1.7 on 2023-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(blank=True, null=True, verbose_name='موجودی کیف پول'),
        ),
    ]
