# Generated by Django 4.1.7 on 2023-09-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_module', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_to_add', models.IntegerField(verbose_name='درصد اضافه شدن به سبد خرید')),
            ],
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='percentage_to_add',
        ),
    ]
