# Generated by Django 4.1.7 on 2023-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_module', '0003_walletsetting_remove_wallet_percentage_to_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی کیف پول'),
        ),
    ]
