# Generated by Django 4.1.7 on 2023-09-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_module', '0004_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.TextField(default=0, max_length=10, verbose_name='موجودی کیف پول'),
        ),
    ]
