# Generated by Django 4.1.7 on 2023-09-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_module', '0006_alter_walletsetting_percentage_to_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='موجودی کیف پول'),
        ),
    ]
