# Generated by Django 4.1.7 on 2023-09-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_module', '0007_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletsetting',
            name='min_purchase',
            field=models.BigIntegerField(default=200000, verbose_name='حداقل خرید'),
        ),
    ]
