# Generated by Django 4.1.7 on 2023-10-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet_module', '0016_alter_transaction_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
    ]
