# Generated by Django 4.1.7 on 2023-08-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0006_alter_contactus_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
    ]
