# Generated by Django 4.1.7 on 2023-08-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0007_remove_contactus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_emailed',
            field=models.BooleanField(default=False, verbose_name='پاسخ ایمیل شده / نشده توسط ادمین'),
        ),
    ]
