# Generated by Django 4.1.7 on 2023-08-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0008_contactus_is_emailed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='متن پاسخ تماس با ما'),
        ),
    ]
