# Generated by Django 4.1.7 on 2023-05-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(to='article_module.articlecategory', verbose_name='دسته بندی محصول'),
        ),
    ]
