# Generated by Django 4.1.7 on 2023-05-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='url_title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان در url'),
        ),
    ]
