# Generated by Django 4.1.7 on 2023-05-22 15:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0004_articletag_alter_article_category_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor.fields.RichTextField(db_index=True, verbose_name='توضیحات'),
        ),
    ]
