# Generated by Django 4.1.7 on 2023-05-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_alter_article_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-create_date'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
