# Generated by Django 4.1.7 on 2023-10-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0007_article_visit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_module.article', verbose_name='مقاله')),
            ],
        ),
    ]
